### ISSUE TITLE
Documentation is outdated and not describing this library

### ISSUE THREAD

**Issue by visto9259** [LM-Commons/LmcRbac#2]
The documentation in the `docs` folder is providing instructions related to LmcRbacMvc.
This is probably because that documentation was there when imported from ZfcRbac which was also referring to the MVC version of ZfcRbac.

**Comment by juuce** [comment]
Hi, Firstly great that you've taken this (these) libraries on board. I'm attempting to use LmcUser and LmcRbac instead of always rolling my own auth system....
I've noticed several inconsistent points in the docs and I'm still trying to integrate LmcUser with LmcAdmin and LmcRbac.

Firstly, there is a very strange and difficult isolation of the right library to use (**laminas-commons**/lmc-user or **lm-commons**/lmc-user and same for rbac and admin modules. I'm using lm-commons/*
I've read your points/discussion as to 'not' use the word lamins in the namespace but am still unclear today which library is used going forward.
_Currently using laminas-mvc 3.1.1_

Secondly trying to use lm-commons/lmc-user: 3.3 causes a hydration error (seems like issue listed). Fall back to 3.2.2 works.

Thirdly, LmcRbc docs references (https://github.com/LM-Commons/LmcRbac/blob/master/docs/04.%20Guards.md )

`use LmcRbac\Guard\GuardInterface;

return [
    'lmc_rbac' => [
        'protection_policy' => GuardInterface::POLICY_DENY
    ]
];`

There is no Gaurd src / namespace...?

I think the first two points are making it difficult for anyone trying to implement these into Laminas MCV (using skeleton).
I personally do not have much experience with the RBAC module so don't know how I can help...

**Comment by visto9259** [comment]
@juuce, the `Laminas-Commons` version should have been marked as "abandoned" quite a while ago.  We'll mark it as such over the weekend.
The documentation for LmcRbac is wrong as stated in this issue.  This is actually LmcRbacMvc documentation.  On the plate as well over the coming weeks.  The LmcUser issue with the hydrator has been reported already.  Looking for bandwidth to fix it.

**Comment by visto9259** [comment]
Closed by #9 and #8.
